title: Satu Metsälampi
email: satu.metsalampi@proton.me
description: >-
    Public economics, Behavioral economics, Experimental economics, Survey methods
baseurl: ""
url: "https://satumetsa.github.io"
twitter_username: SatuMetsalampi
github_username:  satumetsa

# Build settings
theme: minima

header_pages:
  - research.md

plugins:
  - jekyll-feed
